#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh &
killall picom
picom --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII IX X

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Pcmanfm desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
