--archivo de configuracion
require('settings')
require('keymaps')
require('plugins/packer')
require('plugins/pywal')
require('plugins/neotree')
require('plugins/feline')
require('plugins/tabby')
require('plugins/hop')
require('plugins/treesitter')
require('plugins/auto-pairs')
require('plugins/vertical-column')
require('plugins/coc')
require('plugins/twilight')
require('plugins/zen-mode')
require('colors')
